{
 "title": "FastAPI + Fraud AI Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "avg duration"
    }
   ]
  },
  {
   "title": "Model Precision",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 6 },
   "targets": [
    { "expr": "fraud_model_precision", "legendFormat": "precision" }
   ]
  },
  {
   "title": "Model Recall",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 6 },
   "targets": [
    { "expr": "fraud_model_recall", "legendFormat": "recall" }
   ]
  },
  {
   "title": "Model Accuracy",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 8, "h": 6 },
   "targets": [
    { "expr": "fraud_model_accuracy", "legendFormat": "accuracy" }
   ]
  },
  {
   "title": "Feature Drift Score (PSI)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 12, "w": 8, "h": 6 },
   "targets": [
    { "expr": "fraud_model_feature_drift", "legendFormat": "drift score" }
   ]
  },
  {
   "title": "Fraud Transaction Count (Total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 8, "h": 6 },
   "targets": [
    { "expr": "fraud_transactions_total", "legendFormat": "total transactions" }
   ]
  },
  {
   "title": "Fraud Transaction Rate (1m)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 18, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "rate(fraud_transactions_total[1m])",
     "legendFormat": "tx/sec"
    }
   ]
  }
 ]
}